### PR TITLE
42 deployment persistence

### PR DESCRIPTION
**Pull request by darashev-daiteap**
* Add three options for deployment persistence: 
  * `PostgreSQLaaS`(default) - Creates Ionos Postgres Cluster, and configures the connector to use it
  * `PostgreSQL` - Creates a Postgres container, and configures the connector to use it
  * `None` - No persistence
* Add warning message in the documentation and the deployment script if no persistence is selected
* Modify the workflow to create two images

### CODE REVIEW

**Comment by darashev-daiteap** [comment]
This [PR](https://github.com/Digital-Ecosystems/ionos-kubernetes-cluster) is related, because a private lan in the Kubernetes is required.

**Comment by akafazov** [comment]
> This [PR](https://github.com/Digital-Ecosystems/ionos-kubernetes-cluster) is related, because a private lan in the Kubernetes is required.

Link points to repository rather than PR!

**Comment by darashev-daiteap** [comment]
> > This [PR](https://github.com/Digital-Ecosystems/ionos-kubernetes-cluster) is related, because a private lan in the Kubernetes is required.
> 
> Link points to repository rather than PR!

fixed

**Review by paulocabrita-ionos — APPROVED** [review]
LGTM.

**Pull request merged**
